---
title: "Evaluation of global runs"
author: "Beni Stocker"
date: "`r Sys.Date()`"
# output:
#   html_document:
#     toc: true
#     toc_float: true
#     toc_depth: 4
#     number_sections: true
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
header-includes:
   - \usepackage{amsmath}
bibliography: bibliography.bib
---

```{r "knitr config", cache = FALSE, include=FALSE}
require(knitr)
library(rsofun)
library(rbeni)
library(ggplot2)
library(tidyr)
library(broom)
library(viridis)
library(abind)

load_dependencies_rsofun()
```

# Evaluation of GPP against FLUXNET data

## Define file paths
```{r}
fil_pmodel_org_modis  <- "~/sofun_outputs/output_nc_global_sofun/global_ORG_MODIS-C006_MOD15A2_2000_2016.a.gpp.nc"
fil_pmodel_brc_modis  <- "~/sofun_outputs/output_nc_global_sofun/global_BRC_MODIS-C006_MOD15A2_2000_2016.a.gpp.nc"
fil_pmodel_full_modis <- "~/sofun_outputs/output_nc_global_sofun/global_FULL_MODIS-C006_MOD15A2_2000_2016.a.gpp.nc"

fil_pmodel_org_3g  <- "~/sofun_outputs/output_nc_global_sofun/global_ORG_fAPAR3g_v2_2000_2016.a.gpp.nc"
fil_pmodel_brc_3g  <- "~/sofun_outputs/output_nc_global_sofun/global_BRC_fAPAR3g_v2_2000_2016.a.gpp.nc"
fil_pmodel_full_3g <- "~/sofun_outputs/output_nc_global_sofun/global_FULL_fAPAR3g_v2_2000_2016.a.gpp.nc"

fil_pmodel_full_modis_meanann <- "~/sofun_outputs/output_nc_global_sofun/global_FULL_MODIS-C006_MOD15A2_2000_2016.a.gpp_MEANANN.nc"
fil_pmodel_full_3g_meanann    <- "~/sofun_outputs/output_nc_global_sofun/global_FULL_fAPAR3g_v2_2000_2016.a.gpp_MEANANN.nc"

fil_pmodel_simpleorg_3g  <- "~/sofun_outputs/output_nc_global_sofun/global_simpleORG_fAPAR3g_v2_2000_2016.a.gpp.nc"

landfil <- "~/sofun_outputs/output_nc_global_sofun/global_FULL_MODIS-C006_MOD15A2_2000_2016.fland.nc"

fil_pmodel_stocker19 <- "~/data/stocker19natgeo_outputs/s0_fapar3g_v2_global.a.gpp.nc"

fil_mte_meanann     <- "~/data/gpp_mte/gpp_mte_MEANANN.nc"
fil_fluxcom_meanann <- "~/data/gpp_mte/gpp_mte_fluxcom_MEANANN.nc"
fil_vpm_meanann     <- "~/data/sif_gpp_remy_trevor/data_proc/VPM_remy_trevor_MEANANN.nc"
fil_bess_meanann    <- "~/data/sif_gpp_remy_trevor/data_proc/BESS_remy_trevor_MEANANN.nc"
fil_beps_meanann    <- "~/data/sif_gpp_remy_trevor/data_proc/BEPS_remy_trevor_MEANANN.nc"
fil_modis55_meanann <- "~/data/sif_gpp_remy_trevor/data_proc/MODc55_remy_trevor_MEANANN.nc"
fil_modis6_meanann  <- "~/data/sif_gpp_remy_trevor/data_proc/MODc6_remy_trevor_MEANANN.nc"

fil_mte     <- "~/data/gpp_mte/gpp_mte_ANN.nc"
fil_fluxcom <- "~/data/gpp_mte/gpp_mte_fluxcom_ANN.nc"
fil_vpm     <- "~/data/sif_gpp_remy_trevor/data_proc/VPM_remy_trevor_ANN.nc"
fil_bess    <- "~/data/sif_gpp_remy_trevor/data_proc/BESS_remy_trevor_ANN.nc"
fil_beps    <- "~/data/sif_gpp_remy_trevor/data_proc/BEPS_remy_trevor_ANN.nc"
fil_modis55 <- "~/data/sif_gpp_remy_trevor/data_proc/MODc55_remy_trevor_ANN.nc"
fil_modis6  <- "~/data/sif_gpp_remy_trevor/data_proc/MODc6_remy_trevor_ANN.nc"

fil_gome2a <- "~/data/sif_gpp_remy_trevor/data_proc/GOME2A_remy_trevor_MEANANN.nc"
fil_gome2b <- "~/data/sif_gpp_remy_trevor/data_proc/GOME2B_remy_trevor_MEANANN.nc"
```

## Lon/lat fields

### Read data and get differences

```{r}
## Read P-model outputs (mean across years)
nc_pmodel_full_modis_meanann <- read_nc_onefile(fil_pmodel_full_modis_meanann)
nc_pmodel_full_3g_meanann <- read_nc_onefile(fil_pmodel_full_3g_meanann)

## Read other GPP models
nc_mte <- read_nc_onefile(fil_mte_meanann)
nc_fluxcom <- read_nc_onefile(fil_fluxcom_meanann, time_is_years = TRUE)
nc_vpm <- read_nc_onefile(fil_vpm_meanann, time_is_years = TRUE)
nc_bess   <- read_nc_onefile(fil_bess_meanann, date_origin = "1970-01-01")
nc_beps   <- read_nc_onefile(fil_beps_meanann, date_origin = "1970-01-01")
nc_modis55 <- read_nc_onefile( fil_modis55_meanann, time_is_years = TRUE)
nc_modis6  <- read_nc_onefile( fil_modis6_meanann, time_is_years = TRUE)

## Read SiF datasets
nc_gome2a <- read_nc_onefile(fil_gome2a)
nc_gome2b <- read_nc_onefile(fil_gome2b)

## combine and take mean across models
nc_gpp_mean <- nc_mte
nc_gpp_mean$vars$gpp <- abind(
  nc_fluxcom$vars$gpp, 
  nc_mte$vars$gpp, 
  nc_vpm$vars$gpp, 
  nc_bess$vars$gpp, 
  nc_beps$vars$gpp, 
  nc_modis55$vars$gpp, 
  nc_modis6$vars$gpp, 
  along = 3
  ) %>% 
  apply(., c(1,2), FUN = mean, na.rm = TRUE)
  
## mask out gridcells based on P-model grid
nc_gpp_mean$vars$gpp[which(is.na(nc_pmodel_full_3g_meanann$vars$gpp))] <- NA


## combine and take mean across SiF data
nc_sif_mean <- nc_mte
nc_sif_mean$vars$gpp <- abind(
  nc_gome2a$vars$sif, 
  nc_gome2b$vars$sif, 
  along = 3
  ) %>% 
  apply(., c(1,2), FUN = mean, na.rm = TRUE)
  
## mask out gridcells based on P-model grid
nc_sif_mean$vars$sif[which(is.na(nc_pmodel_full_3g_meanann$vars$gpp))] <- NA

plot_map3(nc_gpp_mean)
plot_map3(nc_sif_mean)
```

### Create plots
```{r}
## Mean SiF
map_sif_mean <- plot_map3(
  nc_sif_mean,
  colorscale = viridis,
  plot_title = "SiF: Mean of GOME-2a and GOME-2b",
  plot_subtitle = expression(paste("mW m"^-2, " sr"^-1, " nm"^1, ", annual mean")),
  nbin = 12
  )

## Mean GPP
map_gpp_mean <- plot_map3(
  nc_gpp_mean, 
  colorscale = viridis, 
  nbin = 15, 
  plot_title = "GPP: Mean of other models", 
  plot_subtitle = expression( paste("g C m"^-2, " yr"^-1 ) ), 
  breaks = c(seq(0, 3000, 200), Inf)
  )

## P-model FULL MODIS, load and take mean across time, and map
map_pmodel_full_modis <- plot_map3(
  nc_pmodel_full_modis_meanann, 
  colorscale = viridis, 
  nbin = 15, 
  plot_title = "GPP: P-model", 
  plot_subtitle = expression( paste("g C m"^-2, " yr"^-1, "  FULL, MODIS FPAR" ) ), 
  breaks = c(seq(0, 3000, 200), Inf)
  )

## P-model FULL MODIS, load and take mean across time, and map
map_pmodel_full_3g <- plot_map3(
  nc_pmodel_full_3g_meanann, 
  colorscale = viridis, 
  nbin = 15, 
  plot_title = "GPP: P-model", 
  plot_subtitle = expression( paste("g C m"^-2, " yr"^-1, "  FULL, fAPAR3g" ) ), 
  breaks = c(seq(0, 3000, 200), Inf)
  )

cowplot::plot_grid(map_sif_mean, map_gpp_mean, map_pmodel_full_modis, map_pmodel_full_3g, ncol = 2)
ggsave("fig/maps_comparison.pdf", width = 12, height = 8)
```

<!-- ### Differences -->
<!-- ```{r} -->
<!-- nc_fluxcom <- read_nc_onefile(fil_fluxcom_meanann, time_is_years = TRUE) -->
<!-- nc_fluxcom$vars$gpp <- apply(nc_fluxcom$vars$gpp, c(1,2), FUN = mean) -->
<!-- nc_fluxcom$vars$gpp <- nc_fluxcom$vars$gpp[,360:1] -->

<!-- image(nc_full_3g$vars$gpp) -->
<!-- image(nc_fluxcom$vars$gpp) -->

<!-- diff_pmodel3g_fluxcom <- nc_full_3g -->
<!-- diff_pmodel3g_fluxcom$vars$gpp <- diff_pmodel3g_fluxcom$vars$gpp - nc_fluxcom$vars$gpp -->

<!-- plot_map3(diff_pmodel3g_fluxcom, colorscale = "mycentered", nbin = 10, width = 0.01, breaks = c(-Inf, seq(-1000, 1000, by = 200), Inf), plot_title = expression(paste("Difference P-model - FLUXCOM"))) -->
<!-- ``` -->

## Time series

### Collect data.
```{r}
filn <- "./data/df_tseries.csv"
overwrite <- FALSE

if (!file.exists(filn) || overwrite){
  
df_tseries <- integrate_lonlat(fil_pmodel_full_modis, landfil) %>% 
  rename(gpp_pmodel_full_modis = gpp) %>% 
  left_join(
    integrate_lonlat(fil_pmodel_brc_modis, landfil) %>%
      rename(gpp_pmodel_brc_modis = gpp),
    by = "date"
  )  %>%
  left_join(
    integrate_lonlat(fil_pmodel_org_modis, landfil) %>%
      rename(gpp_pmodel_org_modis = gpp),
    by = "date"
  ) %>%
  left_join(
    integrate_lonlat(fil_pmodel_org_3g, landfil) %>%
      rename(gpp_pmodel_org_3g = gpp),
    by = "date"
  ) %>%
  left_join(
    integrate_lonlat(fil_pmodel_brc_3g, landfil) %>%
      rename(gpp_pmodel_brc_3g = gpp),
    by = "date"
  ) %>%
  left_join(
    integrate_lonlat(fil_pmodel_full_3g, landfil) %>%
      rename(gpp_pmodel_full_3g = gpp),
    by = "date"
  ) %>%
  left_join(
    integrate_lonlat(fil_pmodel_simpleorg_3g, landfil) %>%
      rename(gpp_pmodel_simpleorg_3g = gpp),
    by = "date"
  ) %>%
  mutate(year = year(date)) %>% 
  dplyr::select(-date) %>% 
  left_join(
    integrate_lonlat(fil_pmodel_stocker19, landfil) %>% 
      rename(gpp_pmodel_stocker19 = gpp) %>% 
      mutate(year = year(date)) %>% 
      dplyr::select(-date),
    by = "year"
    ) %>% 
  left_join(
    integrate_lonlat(fil_mte, date_origin = "1970-01-01") %>% 
      rename(gpp_mte = gpp) %>% 
      mutate(year = year(date)) %>% 
      dplyr::select(-date),
    by = "year"
    ) %>% 
  left_join(
    integrate_lonlat(fil_fluxcom, time_is_years = TRUE) %>% 
      rename(gpp_fluxcom = gpp) %>% 
      mutate(year = year(date)) %>% 
      dplyr::select(-date),
    by = "year"
    ) %>% 
  left_join(
    integrate_lonlat(fil_vpm) %>% 
      rename(gpp_vpm = gpp) %>% 
      mutate(year = year(date)) %>% 
      dplyr::select(-date),
    by = "year"
    ) %>% 
  left_join(
    integrate_lonlat(fil_bess) %>% 
      rename(gpp_bess = gpp) %>% 
      mutate(year = year(date)) %>% 
      dplyr::select(-date),
    by = "year"
    ) %>% 
  left_join(
    integrate_lonlat(fil_beps) %>% 
      rename(gpp_beps = gpp) %>% 
      mutate(year = year(date)) %>% 
      dplyr::select(-date),
    by = "year"
    ) %>% 
  left_join(
    integrate_lonlat(fil_modis55) %>% 
      rename(gpp_modis55 = gpp) %>% 
      mutate(year = year(date)) %>% 
      dplyr::select(-date),
    by = "year"
    )  %>% 
  left_join(
    integrate_lonlat(fil_modis6) %>% 
      rename(gpp_modis6 = gpp) %>% 
      mutate(year = year(date)) %>% 
      dplyr::select(-date),
    by = "year"
    )

  ## add co2 data
  df_tseries <- df_tseries %>% 
    left_join(
      readr::read_csv("~/data/co2/cCO2_rcp85_const850-1765.csv") %>% 
        dplyr::filter(year>1750) %>% 
        dplyr::mutate(date = lubridate::ymd(paste0(as.integer(year), "-01-01"))) %>% 
        dplyr::mutate(year = lubridate::year(date)) %>% 
        dplyr::select(-date),
      by = "year"
    )

  write_csv(df_tseries, path = filn)
  
} else {
  df_tseries <- read_csv(filn)
}
```


### Evaluate time series.
```{r}
plot_selection <- c("gpp_pmodel_full_3g", "gpp_pmodel_brc_3g", "gpp_pmodel_org_3g", "gpp_pmodel_full_modis", "gpp_pmodel_brc_modis", "gpp_pmodel_org_modis", "gpp_pmodel_simpleorg_3g", "gpp_mte", "gpp_fluxcom", "gpp_modis55", "gpp_modis6", "gpp_bess", "gpp_beps", "gpp_vpm")

## CAlculate sensitivity to CO2
mynorm <- function(vec){
  out <- vec/vec[1]
  return(out)
}
minus_one <- function(x){x-1.0}

## start only in year 2001 because modis data is not available for jan 2000
df_tseries <- df_tseries %>% 
  filter(!(year==2000))

df_lm_co2 <- df_tseries %>% 
  mutate_all(.funs = mynorm) %>% 
  mutate_all(.funs = minus_one) %>% 
  pivot_longer(cols = starts_with("gpp_"), names_to = "model", values_to = "gpp") %>% 
  mutate( model = factor(model, levels = plot_selection, ordered = TRUE)) %>% 
  group_by(model) %>% 
  nest() %>% 
  mutate(linmod = purrr::map(data, ~lm(gpp ~ co2, data = .))) %>% 
  mutate(tidied = purrr::map(linmod, tidy)) %>% 
  unnest(tidied) %>% 
  filter(term=="co2")

df_lm_year <- df_tseries %>% 
  mutate_at(vars(starts_with("gpp_")), .funs = mynorm) %>% 
  mutate_at(vars(starts_with("gpp_")), .funs = minus_one) %>% 
  pivot_longer(cols = starts_with("gpp_"), names_to = "model", values_to = "gpp") %>% 
  mutate( model = factor(model, levels = plot_selection, ordered = TRUE)) %>% 
  group_by(model) %>% 
  nest() %>% 
  mutate(linmod = purrr::map(data, ~lm(gpp ~ year, data = .))) %>% 
  mutate(tidied = purrr::map(linmod, tidy)) %>% 
  unnest(tidied) %>% 
  filter(term=="year")
  
df_tseries %>% 
  pivot_longer(cols = starts_with("gpp_"), names_to = "model", values_to = "gpp") %>% 
  filter(model %in% plot_selection) %>% 
  filter(!(model=="gpp_pmodel_simpleorg_3g")) %>% 
  ggplot(aes(x = year, y = gpp, color = model)) + 
  geom_line() + 
  # scale_colour_brewer(palette = "Paired") + 
  labs(x = "Year", y =  "GPP (GtC/yr)") +
  scale_color_brewer(palette="Paired")

#ggsave("fig/gpp_vs_year.pdf", width = 7, height = 4)

df_tseries %>% 
  pivot_longer(cols = starts_with("gpp_"), names_to = "model", values_to = "gpp") %>% 
  filter(model %in% plot_selection) %>% 
  ggplot(aes(x = co2, y = gpp, color = model)) + 
  geom_line() + 
  # scale_colour_brewer(palette = "Paired") +
  labs( x = "CO2 (ppm)", y = "GPP (GtC/yr)")
#ggsave("fig/gpp_vs_co2.pdf", width = 7, height = 4)

df_lm_co2 %>% 
  filter(model %in% plot_selection) %>% 
  ggplot(aes(x = model, y = estimate)) +  #, 
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin = estimate - std.error, ymax = estimate + std.error), position=position_dodge(), width = 0.2) +
  labs(x = "Model", y = "dGPP/GPP / dCO2/CO2") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
#ggsave("fig/barplot_co2_sensitivity.pdf", width = 6, height = 5)

df_lm_year %>% 
  filter(model %in% plot_selection) %>% 
  ggplot(aes(x = model, y = estimate)) +  #, 
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin = estimate - std.error, ymax = estimate + std.error), position=position_dodge(), width = 0.2) +
  labs(x = "Model", y = "dGPP/GPP / dyear/year") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
#ggsave("fig/barplot_year_sensitivity.pdf", width = 6, height = 5)

df_tseries %>% 
  filter(year %in% 2001:2011) %>% 
  summarise_all(.funs = mean)
```


## Latitudinal distribution

### Collect data

```{r}
## Get common mask
mask <- nc_gpp_mean$vars$gpp
mask[is.na(nc_sif_mean$vars$gpp)] <- NA
mask[is.na(nc_pmodel_full_modis_meanann$vars$gpp)] <- NA

filn <- "./data/df_lat.csv"
overwrite <- TRUE
if (!file.exists(filn) || overwrite){
  
  df_lat <- integrate_lon(ifil = fil_pmodel_full_modis_meanann, landfil = landfil, mask = mask, method = "mine") %>% 
    rename( gpp_pmodel_full_modis = gpp ) %>% 
    left_join(
      integrate_lon(ifil = fil_pmodel_full_3g_meanann, landfil = landfil, mask = mask, method = "mine") %>%
        rename( gpp_pmodel_full_3g = gpp),
      by = "lat"
    ) %>%
    left_join(
      integrate_lon(ifil = fil_mte_meanann, mask = mask, method = "mine", time_is_years = TRUE) %>% 
        rename( gpp_mte = gpp),
      by = "lat"
    ) %>% 
    left_join(
      integrate_lon(ifil = fil_fluxcom_meanann, mask = mask, method = "mine", time_is_years = TRUE) %>% 
        rename( gpp_fluxcom = gpp),
      by = "lat"
    ) %>% 
    left_join(
      integrate_lon(ifil = fil_bess_meanann, mask = mask, method = "mine") %>% 
        rename( gpp_bess = gpp),
      by = "lat"
    ) %>% 
    left_join(
      integrate_lon(ifil = fil_beps_meanann, mask = mask, method = "mine") %>% 
        rename( gpp_beps = gpp),
      by = "lat"
    ) %>% 
    left_join(
      integrate_lon(ifil = fil_vpm_meanann, mask = mask, method = "mine") %>% 
        rename( gpp_vpm = gpp),
      by = "lat"
    ) %>% 
    left_join(
      integrate_lon(ifil = fil_modis55_meanann, mask = mask, method = "mine") %>% 
        rename( gpp_modis55 = gpp),
      by = "lat"
    ) %>% 
    left_join(
      integrate_lon(ifil = fil_modis6_meanann, mask = mask, method = "mine") %>% 
        rename( gpp_modis6 = gpp),
      by = "lat"
    ) %>% 
    left_join(
      # integrate_lon_sif(fil_sif, "~/data/gome_2_sif_downscaled/data_halfdeg/gridarea.nc", mask = mask, method = "mine"),
      integrate_lon(ifil = fil_gome2a, mask = mask, method = "mine") %>% 
        rename( sif_gome2a = sif ),
      by = "lat"
    ) %>% 
    left_join(
      # integrate_lon_sif(fil_sif, "~/data/gome_2_sif_downscaled/data_halfdeg/gridarea.nc", mask = mask, method = "mine"),
      integrate_lon(ifil = fil_gome2b, mask = mask, method = "mine") %>% 
        rename( sif_gome2b = sif ),
      by = "lat"
    )

    write_csv(df_lat, path = filn)
  
} else {
  df_lat <- read_csv(filn)
}
```

### Evaluate latitudinal distribution

```{r}
plot_selection <- c("gpp_mte", "gpp_fluxcom", "gpp_modis55", "gpp_modis6", "gpp_bess", "gpp_beps", "gpp_vpm")

df_long <- df_lat %>% 
      pivot_longer(cols = starts_with("gpp_"), names_to = "model", values_to = "gpp" ) %>% 
      filter(model %in% plot_selection) %>% 
      mutate( model = factor(model, levels = plot_selection, ordered = TRUE))


# scaleme <- max(df_lat$gpp_pmodel_full_modis)/max(df_lat$sif, na.rm=TRUE)
scaleme <- 1600

myjcolors <- function(ncolors){
  
  jcols <- jcolors::jcolors("default")
  
  ## add
  out <- c(jcols, gplots::col2hex("darkgreen"), gplots::col2hex("navyblue"), gplots::col2hex("darkgoldenrod"), gplots::col2hex("orchid") )
  names(out) <- c(names(jcols), "darkgreen", "navyblue", "darkgoldenrod", "orchid")
  
  out <- out[1:ncolors]
  return(out)
}

# df_lat %>% 
#   pivot_longer(cols = starts_with("gpp_"), names_to = "model", values_to = "gpp" ) %>% 
#   ggplot(aes(x = lat, y = gpp, color = model))+
#   geom_line()


ggplot() +

  ## lines for other GPP models 
  geom_line(
    data = df_long,
    aes(x = lat, y = gpp * 1e-15, color = model),
    size = 0.5
    ) +

  ## Lines for Sif
  geom_line(data = df_lat, aes(x = lat, y = sif_gome2b * scaleme * 1e-15, size = "GOME-2b"), color = "grey50") +
  geom_line(data = df_lat, aes(x = lat, y = sif_gome2a * scaleme * 1e-15, size = "GOME-2a"), color = "black") +

  ## Lines for P-model
  geom_line(data = df_lat, aes(x = lat, y = gpp_pmodel_full_modis * 1e-15, alpha = "P-model MODIS FPAR"), color = "springgreen3", size = 1.0) +
  geom_line(data = df_lat, aes(x = lat, y = gpp_pmodel_full_3g * 1e-15,    alpha = "P-model fAPAR3g"),    color = "firebrick1", size = 1.0) +

  ## right y-axis for sif
  scale_y_continuous(sec.axis = sec_axis(~.*scaleme, name = expression(paste("SiF (TW sr"^-1, " nm"^1, ")")))) +

  ## legend for GPP models
  scale_colour_manual(values = myjcolors(7) %>% unlist() %>% unname(), label = c("MTE", "FLUXCOM", "MODIS 5.5", "MODIS 6.0", "BESS", "BEPS", "VPM"), name = "Other GPP models") +
  # scale_colour_brewer(palette = "Set1", label = c("MTE", "FLUXCOM", "MODIS 5.5", "MODIS 6.0", "BESS", "BEPS", "VPM"), name = "Other GPP models") +

  ## legend for P-model
  scale_alpha_manual(
    name = "GPP P-mdel", values = c(1.0, 1.0),
    guide = guide_legend(override.aes = list(color=c("firebrick1", "springgreen3")))
    ) +

  ## legend for SiF
  scale_size_manual(
    name = "SiF", values = c(1.0, 1.0),
    guide = guide_legend(override.aes = list(color=c("grey50", "black")))
    ) +

  xlim( -55, 80 ) +
  labs(
    x = expression(paste("Latitude (", degree, "N)")), 
    y = expression( paste("GPP (Pg yr"^-1, ")" ) )
    )

ggsave("fig/gpp_by_latitude.pdf", width = 7, height = 4)
```

