---
title: "Site selection"
author: "Beni Stocker"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    number_sections: true
# output:
#   pdf_document:
#     toc: true
#     toc_depth: 3
#     number_sections: true
header-includes:
   - \usepackage{amsmath}
bibliography: beni.bib
csl: nature.csl
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(readr)
library(dplyr)
library(rsofun)
```


First, get the 68 calibration sites as a vector.
```{r message=FALSE, warning=FALSE}
calibsites <- readr::read_csv( "/alphadata01/bstocker/data/flue/flue_stocker18nphyt.csv" ) %>%
              dplyr::filter( !is.na(cluster) ) %>%
              dplyr::select( site ) %>%
              distinct() %>%

              ## additionally exclude C4
              dplyr::filter( !(site %in% dplyr::filter(metainfo_Tier1_sites_kgclimate_fluxnet2015, c4 )$sitename) ) %>%

              dplyr::select( site ) %>%
              unlist()
```

Then, use the `metainfo_Tier1_sites_kgclimate_fluxnet2015` data frame and add this info.
```{r siteoverview, warning=FALSE, message=FALSE}
siteinfo <- rsofun::metainfo_Tier1_sites_kgclimate_fluxnet2015 %>%
            dplyr::filter( c4 %in% c(FALSE, NA) & classid != "CRO" ) %>%
            mutate( calib = ifelse(sitename %in% calibsites, "Y", "") ) %>%
            # mutate( Reference = paste0("[@", sitename ,"]") )
            mutate( Reference = paste0("cite{", sitename ,"}") )

## add number of daily GPP values in NT
load("./data/obs_eval_NT.Rdata")
siteinfo <- obs_eval_NT$ddf %>% 
  dplyr::select( sitename, gpp_obs ) %>% 
  tidyr::drop_na() %>% 
  group_by( sitename ) %>%
  summarise( ndaily_gpp = n() ) %>% 
  right_join( siteinfo, by="sitename" ) %>% 
  tidyr::drop_na( ndaily_gpp )

siteinfo_table <- siteinfo %>%
          mutate( Period = paste0(as.character(year_start), "-", as.character(year_end)) ) %>%
          dplyr::select( -year_start, -year_end ) %>%
          dplyr::rename( Site=sitename, Lon.=lon, Lat.=lat, Elevation=elv, Veg.=classid, Clim.=koeppen_code, N = ndaily_gpp, Calib.=calib ) %>%
          dplyr::select( Site, Lon., Lat., Period, Veg., Clim., N, Calib., Reference )

siteinfo_table %>% knitr::kable( caption = "Sites used for calibration. Lon. is longitude, negative values indicate west longitude; Lat. is latitude, positive values indicate north latitude; Veg. is vegetation type: deciduous broadleaf forest (DBF); evergreen broadleaf forest (EBF); evergreen needleleaf forest (ENF); grassland (GRA); mixed deciduous and evergreen needleleaf forest (MF); savanna ecosystem (SAV); shrub ecosystem (SHR); wetland (WET)." )
```

Plot a map.
```{r siteoverview_fig, echo=FALSE, warning=FALSE}
suppressMessages(require(ncdf4, quietly = TRUE))
ncfiln <- "/alphadata01/bstocker/data/greve/ep_over_p_cru_ncep.nc"
if (!file.exists(ncfiln)) {
  epop <- array( 1, dim=c(720,360) )
} else {
  nc <- nc_open( ncfiln )
  epop <- ncvar_get( nc, varid="EP_OVER_P_CRU_NCEP" )
}
source("plot_map_siteoverview.R")
suppressMessages( plot_map_siteoverview( siteinfo, 1/epop, plotfiln="fig/map_sites.pdf" ) ) # 
# cap_siteoverview_fig <- fig_nums( "siteoverview_fig", caption=" Geographical distribution of sites selected for the bias evaluation. Sites listed in Table S1 as group 1 are in green, sites of group 2 are in black. The color of land area represents aridity, quantified as the ratio of precipitation over potential evapotranspiration  from Greve et al.[@greve14]" )
```


Export table
```{r}
source("create_table_latex.R")
create_table_latex(siteinfo_table, caption="caption", filn="table.tex")
```


```{r}
print(paste("Number of sites for calibration: ", length(calibsites)))
print(paste("Number of sites for evaluation: ", nrow(siteinfo_table)))
ncalib <- siteinfo %>% dplyr::filter(calib=="Y") %>% summarise( total=sum(ndaily_gpp) )
print(paste("Number of daily data points for calibration: ", ncalib))
neval <- siteinfo %>% summarise( total=sum(ndaily_gpp) )
print(paste("Number of daily data points for calibration: ", neval))

## C4 vegetation
metainfo_Tier1_sites_kgclimate_fluxnet2015 %>%
            dplyr::filter( !(c4 %in% c(FALSE, NA)) ) %>% 
            select(sitename) %>% 
            unlist()
```

# References